### ISSUE TITLE
How to open? 

### ISSUE THREAD

**Issue by ryudious** [WSTxda/Plugin-VoiceGPT#1]
I set it as default but there is no way to open it!  Google assitant doesn't even open.  There is NO way to activate this.

**Comment by WSTxda** [comment]
you can ope in like openin google assistant. press power button, swipe gesture in navbar.

**Comment by WSTxda** [comment]
New release you can run and setup it, check it now

**Comment by ryudious** [comment]
Nvm!  It works!  I got it! Thanks boss!
