### ISSUE TITLE
"Activity not found" issue 



### ISSUE THREAD

**Issue by Darkloresider** [WSTxda/Plugin-VoiceGPT#11]
ChatGPT app version 1.2024.087, VoiceGPT latest version. 
When trying to activate assistant mode from voice gpt, there is a forwarding to the ChatGPT page in the play market, in the activity launcher there is not a single item that would be responsible for calling the assistant mode.

**Comment by hackerharis3** [comment]
Same problem for me also

**Comment by AndyLinyeye** [comment]
same problems

**Comment by Cypherthegreat** [comment]
Hi I'm having the same issue however this could be the fact I am. Beta tester. Could you please check that thank you for your work.

**Comment by MajorFoxDie** [comment]
Hey I had the same issue, here's how I fixed it:

1. Uninstall ChatGPT
2. Install the plugin
3. Launch the plugin and install chatgpt when you get taken to the app store.
It should now work.
