### ISSUE TITLE
Volume super low.

### ISSUE THREAD

**Issue by DaddyzG1rl** [WSTxda/Plugin-VoiceGPT#13]
On my phone with android 13 the volumr is low no matter what. On another phone with android 11, no issue.nor on an old phone running android 8.

**Comment by WSTxda** [comment]
> On my phone with android 13 the volumr is low no matter what. On another phone with android 11, no issue.nor on an old phone running android 8. 

Unfortunately, it could be something on your system or the device itself.

**Comment by Fan4eGGG** [comment]
> on your system or the device itself

nah. i can attest it. On formums, ppl often complain about the quiet sound of the voice assistant.

**Comment by luchfilip** [comment]
works fine on Pixel 8 Pro. Super loud. Could you run the app from Android Studio or drop some logs?

**Comment by WSTxda** [comment]
> > on your system or the device itself
> 
> nah. i can attest it. On formums, ppl often complain about the quiet sound of the voice assistant.

So I assume it's not a problem with the application in question

Please check if people who own your device, or device rom face the same problem

**Comment by m-a-x-s-e-e-l-i-g** [comment]
- The app switched over from my main "loud" speaker to the secondary ear speaker.

After some testing I found out that this has to do with my phone being connected to my laptop via Bluetooth.
![Screenshot_20240717-140052.png](https://github.com/user-attachments/assets/6f980774-a2ab-41b7-a26c-5de6bcd52e4a)

After disabling the "Phone calls" option, VoiceGPT works as normal again.

Also, this fixes an issue with VoiceGPT starting slowly, and the microphone not working.
