### ISSUE TITLE
Back button should close the app. 

### ISSUE THREAD

**Issue by m-a-x-s-e-e-l-i-g** [WSTxda/Plugin-VoiceGPT#17]
Current: I press the back button, the UI gets hidden, but VoiceGPT keeps talking and recording. 

Expected: I press the back button, the UI gets hidden, VoiceGPT stops talking and recording.

**Comment by WSTxda** [comment]
Note that this application is responsible for launching the assistant activity through gestures and buttons, and that unexpected behavior is the responsibility of the ChatGPT application.
