### ISSUE TITLE
No relevant setting options found

### ISSUE THREAD

**Issue by chenpingtao2000** [WSTxda/Plugin-VoiceGPT#2]
My redmi phone cannot find the setting options for this plug-in

**Comment by WSTxda** [comment]
Try it:

Apps>Manage Apps>Tap tree dots option in top>Other Settings>Default apps>Assist & voice input>Digital Assistant app

Select VoiceGPT

**Comment by WSTxda** [comment]
New release you can run and setup it, check it now
