### ISSUE TITLE
Try open ChatGPT activity, closes voice input unexpectedly.

### ISSUE THREAD

**Issue by mithu2649** [WSTxda/Plugin-VoiceGPT#20]
When assistant is triggered, it shows connecting for some milliseconds and then closes unexpectedly.
![gif-20240811-235229](https://github.com/user-attachments/assets/be2fe766-b054-4a8c-b72d-d5d850cb5fa5)

**Comment by WSTxda** [comment]
Has voice chat been configured in chatgpt? unfortunately this is something on openai's side

**Comment by WSTxda** [comment]
ok, i can reproduce this now, really need fix in ChatGPT app side

**Comment by Fan4eGGG** [comment]
same. so we just wait for the fix from openai, right?

**Comment by WSTxda** [comment]
> same. so we just wait for the fix from openai, right?

yes, otherwise you can choose to downgrade ChatGPT app

**Comment by sumedhctrl** [comment]
yes i had this issue aswell to fix it just reinstall both apps and exit the beta mode on chatgpt

**Comment by WSTxda** [comment]
@mithu2649 would you be in the ChatGPT beta program too?

**Comment by mithu2649** [comment]
No, I am not currently in the beta program.

**Comment by WSTxda** [comment]
Last release it's working again. Can anyone confirm?

![Screenshot_2024-09-03-16-36-38-244_com.openai.chatgpt.jpg](https://github.com/user-attachments/assets/1783e106-c6e0-4ae4-8620-d02f23611211)

**Comment by mithu2649** [comment]
**It's working again!!**
