### ISSUE TITLE
Any way to open apps via command?

### ISSUE THREAD

**Issue by MUSTAFA-A-KHAN** [WSTxda/Plugin-VoiceGPT#21]
Is there any way to use this assistant similar to Google Assistant, such as:

- Making phone calls
- Opening applications
- Performing other actions?

**Comment by WSTxda** [comment]
No, as it is not possible with the ChatGPT app.

**Comment by MUSTAFA-A-KHAN** [comment]
Yeah sounds reasonable 🥲
