### ISSUE TITLE
GPT voice is coming from ringtone volume

### ISSUE THREAD

**Issue by Tanteisan** [WSTxda/Plugin-VoiceGPT#24]
I can control my Voice Gpt volume by ringtone volume slider/ caller volume slider, but not through media volume. Which makes the sound very low to hear. I use lineageos 21 on samsung phone 
https://github.com/user-attachments/assets/14dca0fb-f624-49da-b999-f644362711f4

**Comment by Good-Vibes-Chat-N-Chew-UK** [comment]
🙁 That's not VideoGPT's fault. It's a ChatGPT problem. I also have this issue but there's no way to fix it. 🙁
