### ISSUE TITLE
VoiceGPT should stop if no more input is said.

### ISSUE THREAD

**Issue by Good-Vibes-Chat-N-Chew-UK** [WSTxda/Plugin-VoiceGPT#27]
VoiceGPT should stop if no more input is said. Otherwise it listens all the time. 😄

**Comment by WSTxda** [comment]
This is from the ChatGPT application side, you can disable this in the settings

**Comment by Good-Vibes-Chat-N-Chew-UK** [comment]
Where in settings?

**Comment by WSTxda** [comment]
> Where in settings?

![Screenshot_2024-09-22-10-28-20-645_com.openai.chatgpt-edit.jpg](https://github.com/user-attachments/assets/73245057-f806-4abf-92bf-d48923ceec18)
