### ISSUE TITLE
Gpt4

### ISSUE THREAD

**Issue by giuliastro** [WSTxda/Plugin-VoiceGPT#3]
Hello, thank you for this nice app.
Is there a way to make the plugin use GPT-4 instead of GPT3.5? I have a pro account on ChatGPT but still it uses GPT3. 5.

Thank you in advance.

**Comment by WSTxda** [comment]
I believe it was the developers' decision to use GPT-4 due to the faster response time in GPT-3.5, anyway I can't determine which version should be used.
