### ISSUE TITLE
"Hey Google" like word in Plugin-VoiceGpt

### ISSUE THREAD

**Issue by vikramisdev** [WSTxda/Plugin-VoiceGPT#8]
So first of all thanks for maiking this app !! I was curious about adding a feature like the google assistant to open up the assistant bottomsheet panel to this plugin so that it becomes easy to communicate with the chatgpt. I think you should consider it and implement it if it is possible. 😃

**Comment by Jastroger** [comment]
+1
Also it should stop if no more input is said. Otherwise it listens all the time

**Comment by WSTxda** [comment]
Unfortunately, voice recognition is something that requires the privileges of a system application to be able to monitor the microphone from end to end.

It is not possible and unfeasible to implement this feature

**Comment by vikramisdev** [comment]
> Unfortunately, voice recognition is something that requires the privileges of a system application to be able to monitor the microphone from end to end.
> 
> It is not possible and unfeasible to implement this feature

If you find any alternative way to implement it, please do add this feature.

**Comment by WSTxda** [comment]
Does not exist, applications without system privileges are strictly prohibited from accessing the end-to-end microphone

**Comment by vi-vlasov** [comment]
Hi, it would be great if chatgpt would take screen context into account if possible.
There is a similar function in gemini

**Comment by richaardvark** [comment]
> Does not exist, applications without system privileges are strictly prohibited from accessing the end-to-end microphone

If our phone is rooted (mine is) wouldn't we be able to accomplish this and install VoiceGPT as a system app?
