### ISSUE TITLE
Google assistant still shows up when I use my headphones assistant button

### ISSUE THREAD

**Issue by DeltriDev** [WSTxda/Plugin-VoiceGPT#9]
First of all, wow, that's a cool plugin you got there, very helpful. It works nicely so far, on feature that would be very nice is being able to wake up chatgpt using my earphones, the assistant button there currently wakes up normal google assistant. Is it even possible?

**Comment by WSTxda** [comment]
Hello, thanks for the feedback, unfortunately it is not possible to replace Google Assistant in this sense, many Google Assistant features are possible because it is a system application and has super permissions such as listening to the device's microphone from end to end, which is a conventional app is disabled.

**Comment by DeltriDev** [comment]
That's kinda unfortunate. Perhaps you could check open apps and if it detects Google assistant it should open gpt? Does that require system permissions too? (Probably yes but I don't know)

**Comment by DrFr33ze** [comment]
This also applies for the assistant function on wear os?

**Comment by DeltriDev** [comment]
> This also applies for the assistant function on wear os? Have to test Android Auto with the cars voice access button at the steering wheel

I don't know, don't use Android Auto and I don't have a wearOS device (yet!)

**Comment by DrFr33ze** [comment]
> > This also applies for the assistant function on wear os? Have to test Android Auto with the cars voice access button at the steering wheel
> 
> I don't know, don't use Android Auto and I don't have a wearOS device (yet!)

Can confirm now, that both cases do not work. Thanks anyway!

**Comment by arendtio** [comment]
@WSTxda I am not sure if your assumption is correct.

When I long-press my Bluetooth headphones (Shokz OpenSwim Pro), my phone asks me which app to use (and if I want to use it as the default). Sadly, it only presents me with Bixby, Alexa, and Google. VoiceGPT is not part of that list, even though it is configured as the default assistant app and works excellent when pressing the phone's home button.

I don't know what capability/permission an app needs to be included in that list, but the dialog looks like the normal 'choose a default app for that action' dialog. Once I select an app as the default, I can reset the dialog to ask again by opening the settings of the app that is being opened and deleting the 'Set as default' connections.

It would be a super cool feature to be able to start VoiceGPT via the headphone button ;-)

**Comment by arendtio** [comment]
@WSTxda adding the following line to the default intent filter in the AndroidManifest works with my setup:

``` XML
<action android:name="android.intent.action.VOICE_COMMAND" />
```

When I long-press the button on my headset, my phone asks me which app I want to use (when I do it the first time), and now I can choose VoiceGPT. Afterward, I can invoke VoiceGPT via my headset. Now, I want to be able to stop the conversation via the button :D

**Comment by WSTxda** [comment]
Thanks everyone, I'll add this
